clear
close all
clc

%% File names

comsol_bone_file = ...
    'rockfish_withbone_dorsoventral_TS.csv';

comsol_no_bone_file = ...
    'rockfish_dorsoventral_TS.csv';

chu_file = 'rockfish_Chu.csv';

output_file = fullfile( ...
    pwd, ...
    'rockfish_dorsoventral_TS_vs_ka_bone_comparison.png');

%% Physical parameters for ka

equivalent_radius_m = 1.4e-2;  % 14 mm
water_sound_speed   = 1500;     % m/s

%% Plot formatting

chu_color     = [0.00 0.00 0.00];  % black
bone_color    = [0.85 0.10 0.10];  % red
no_bone_color = [0.00 0.45 0.74];  % blue

chu_line_width    = 4.5;
comsol_line_width = 4.5;

marker_size = 12;
marker_step = 4;

axis_font_size   = 25;
label_font_size  = 29;
title_font_size  = 34;
legend_font_size = 23;
axis_line_width  = 2.5;

%% Import COMSOL model with bone

bone_data = read_two_column_data( ...
    comsol_bone_file, ...
    'COMSOL model with bone');

f_bone  = bone_data(:,1);
TS_bone = bone_data(:,2);

%% Import COMSOL model without bone

no_bone_data = read_two_column_data( ...
    comsol_no_bone_file, ...
    'COMSOL model without bone');

f_no_bone  = no_bone_data(:,1);
TS_no_bone = no_bone_data(:,2);

%% Import Chu analytical model

chu_data = read_two_column_data( ...
    chu_file, ...
    'Chu analytical model');

f_chu  = chu_data(:,1);
TS_chu = chu_data(:,2);

%% Remove nonpositive frequencies

valid_bone = f_bone > 0;

f_bone  = f_bone(valid_bone);
TS_bone = TS_bone(valid_bone);

valid_no_bone = f_no_bone > 0;

f_no_bone  = f_no_bone(valid_no_bone);
TS_no_bone = TS_no_bone(valid_no_bone);

valid_chu = f_chu > 0;

f_chu  = f_chu(valid_chu);
TS_chu = TS_chu(valid_chu);

if isempty(f_bone)
    error([ ...
        'The COMSOL file with bone contains ', ...
        'no positive frequencies.']);
end

if isempty(f_no_bone)
    error([ ...
        'The COMSOL file without bone contains ', ...
        'no positive frequencies.']);
end

if isempty(f_chu)
    error([ ...
        'The Chu analytical file contains ', ...
        'no positive frequencies.']);
end

%% Sort all datasets by frequency

[f_bone, bone_order] = sort(f_bone);
TS_bone = TS_bone(bone_order);

[f_no_bone, no_bone_order] = sort(f_no_bone);
TS_no_bone = TS_no_bone(no_bone_order);

[f_chu, chu_order] = sort(f_chu);
TS_chu = TS_chu(chu_order);

%% Remove duplicate frequencies

[f_bone, unique_bone] = unique( ...
    f_bone, ...
    'stable');

TS_bone = TS_bone(unique_bone);

[f_no_bone, unique_no_bone] = unique( ...
    f_no_bone, ...
    'stable');

TS_no_bone = TS_no_bone(unique_no_bone);

[f_chu, unique_chu] = unique( ...
    f_chu, ...
    'stable');

TS_chu = TS_chu(unique_chu);

%% Interpolate Chu values at COMSOL frequencies

% These values are used only for displaying Chu markers at the same
% frequencies as the with-bone COMSOL model.
TS_chu_at_bone = interp1( ...
    log10(f_chu), ...
    TS_chu, ...
    log10(f_bone), ...
    'linear', ...
    NaN);

%% Convert frequency to ka

ka_bone = ...
    2*pi*f_bone*equivalent_radius_m / ...
    water_sound_speed;

ka_no_bone = ...
    2*pi*f_no_bone*equivalent_radius_m / ...
    water_sound_speed;

ka_chu = ...
    2*pi*f_chu*equivalent_radius_m / ...
    water_sound_speed;

fprintf( ...
    'Equivalent radius used for ka: %.2f mm\n', ...
    equivalent_radius_m*1000);

fprintf( ...
    'Water sound speed used for ka: %.1f m/s\n', ...
    water_sound_speed);

%% Determine ka-axis limits

all_ka = [ ...
    ka_bone(:)
    ka_no_bone(:)
    ka_chu(:)
    ];

ka_min = min(all_ka);
ka_max = max(all_ka);

%% Marker locations

bone_marker_indices = ...
    1:marker_step:numel(ka_bone);

no_bone_marker_indices = ...
    1:marker_step:numel(ka_no_bone);

%% Create figure

fig = figure( ...
    'Color', 'w', ...
    'Position', [80 60 1250 850]);

ax = axes(fig);
hold(ax, 'on');

%% Chu analytical curve

h_chu = semilogx( ...
    ax, ...
    ka_chu, ...
    TS_chu, ...
    '-', ...
    'Color', chu_color, ...
    'LineWidth', chu_line_width);

%% Chu markers at COMSOL ka values

semilogx( ...
    ax, ...
    ka_bone, ...
    TS_chu_at_bone, ...
    'o', ...
    'LineStyle', 'none', ...
    'MarkerIndices', bone_marker_indices, ...
    'MarkerSize', marker_size, ...
    'MarkerEdgeColor', chu_color, ...
    'MarkerFaceColor', chu_color, ...
    'HandleVisibility', 'off');

%% COMSOL model with bone

h_bone = semilogx( ...
    ax, ...
    ka_bone, ...
    TS_bone, ...
    '-o', ...
    'Color', bone_color, ...
    'LineWidth', comsol_line_width, ...
    'MarkerIndices', bone_marker_indices, ...
    'MarkerSize', marker_size, ...
    'MarkerEdgeColor', bone_color, ...
    'MarkerFaceColor', 'none');

%% COMSOL model without bone

h_no_bone = semilogx( ...
    ax, ...
    ka_no_bone, ...
    TS_no_bone, ...
    '-s', ...
    'Color', no_bone_color, ...
    'LineWidth', comsol_line_width, ...
    'MarkerIndices', no_bone_marker_indices, ...
    'MarkerSize', marker_size, ...
    'MarkerEdgeColor', no_bone_color, ...
    'MarkerFaceColor', 'none');

%% Logarithmic ka axis

set(ax, 'XScale', 'log');

xlim(ax, [ka_min ka_max]);
ylim(ax, [-80 10]);

% Create evenly spaced ticks in logarithmic space.
num_x_ticks = 8;

ka_ticks = logspace( ...
    log10(ka_min), ...
    log10(ka_max), ...
    num_x_ticks);

xticks(ax, ka_ticks);
xticklabels(ax, compose('%.2g', ka_ticks));

%% Labels and title

xlabel(ax, ...
    'ka', ...
    'FontSize', label_font_size, ...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic');

ylabel(ax, ...
    'Target strength (dB re 1 m)', ...
    'FontSize', label_font_size, ...
    'FontWeight', 'bold');

title(ax, ...
    'Rockfish Target Strength', ...
    'FontSize', title_font_size, ...
    'FontWeight', 'bold');

%% Legend

legend(ax, ...
    [h_chu, h_bone, h_no_bone], ...
    {'Chu analytical model', ...
     'COMSOL model with bone', ...
     'COMSOL model without bone'}, ...
    'Location', 'best', ...
    'FontSize', legend_font_size, ...
    'FontWeight', 'bold', ...
    'Box', 'on');

%% Final plot formatting

grid(ax, 'on');
box(ax, 'on');

ax.FontSize   = axis_font_size;
ax.FontWeight = 'bold';
ax.LineWidth  = axis_line_width;

ax.XMinorGrid = 'on';
ax.YMinorGrid = 'on';

ax.GridAlpha      = 0.20;
ax.MinorGridAlpha = 0.10;

ax.TickDir = 'out';
ax.Layer   = 'top';

%% Export figure

exportgraphics( ...
    fig, ...
    output_file, ...
    'Resolution', 300);

fprintf('Figure saved to:\n%s\n', output_file);

%% Local function

function data = read_two_column_data(file_name, data_label)

    data = readmatrix( ...
        file_name, ...
        'CommentStyle', '%');

    if size(data, 2) < 2
        error([ ...
            'The %s file must contain at least two columns: ', ...
            'frequency and target strength.'], ...
            data_label);
    end

    % Retain the first two columns and remove headers, blank rows,
    % and other nonnumeric entries.
    data = data(:,1:2);

    valid_rows = all(isfinite(data), 2);
    data = data(valid_rows, :);

    if isempty(data)
        error( ...
            'No valid numerical data were found in the %s file.', ...
            data_label);
    end
end